import json
import os
qutewal_dynamic_loading = False
home = os.getenv('HOME')
colors_relative = '.cache/wal/colors.json'
daemon_relative = '.config/qutebrowser/qutewald.py'
colors_absolute = os.path.join(home, colors_relative)
daemon_absolute = os.path.join(home, daemon_relative)
if os.path.isfile(colors_absolute):
    with open(colors_absolute) as colorfile:
        colors = json.load(colorfile)
        cursor = colors['special']['cursor']
        background = colors['special']['background']
        foreground = colors['special']['foreground']
        black = colors['colors']['color0']
        white = colors['colors']['color7']
        gray = colors['colors']['color8']
        red = colors['colors']['color1']
        green = colors['colors']['color2']
        yellow = colors['colors']['color3']
        blue = colors['colors']['color4']
        magenta = colors['colors']['color5']
        cyan = colors['colors']['color6']
    c.colors.completion.category.bg = background
    c.colors.completion.category.border.bottom = background
    c.colors.completion.category.border.top = background
    c.colors.completion.category.fg = foreground
    c.colors.completion.even.bg = background
    c.colors.completion.odd.bg = background
    c.colors.completion.fg = foreground
    c.colors.completion.item.selected.bg = gray
    c.colors.completion.item.selected.border.bottom = background
    c.colors.completion.item.selected.border.top = background
    c.colors.completion.item.selected.fg = foreground
    c.colors.completion.match.fg = yellow
    c.colors.completion.scrollbar.bg = background
    c.colors.completion.scrollbar.fg = gray
    c.colors.downloads.bar.bg = background
    c.colors.downloads.error.bg = red
    c.colors.downloads.error.fg = foreground
    c.colors.downloads.stop.bg = cyan
    c.colors.downloads.system.bg = 'none'
    c.colors.hints.bg = yellow
    c.colors.hints.fg = background
    c.colors.hints.match.fg = blue
    c.colors.keyhint.bg = background
    c.colors.keyhint.fg = foreground
    c.colors.keyhint.suffix.fg = yellow
    c.colors.messages.error.bg = red
    c.colors.messages.error.border = red
    c.colors.messages.error.fg = foreground
    c.colors.messages.info.bg = blue
    c.colors.messages.info.border = blue
    c.colors.messages.info.fg = foreground
    c.colors.messages.warning.bg = red
    c.colors.messages.warning.border = red
    c.colors.messages.warning.fg = foreground
    c.colors.prompts.bg = background
    c.colors.prompts.border = '1px solid ' + background
    c.colors.prompts.fg = foreground
    c.colors.prompts.selected.bg = magenta
    c.colors.statusbar.caret.bg = cyan
    c.colors.statusbar.caret.fg = cursor
    c.colors.statusbar.caret.selection.bg = cyan
    c.colors.statusbar.caret.selection.fg = foreground
    c.colors.statusbar.command.bg = background
    c.colors.statusbar.command.fg = foreground
    c.colors.statusbar.command.private.bg = background
    c.colors.statusbar.command.private.fg = foreground
    c.colors.statusbar.insert.bg = green
    c.colors.statusbar.insert.fg = background
    c.colors.statusbar.normal.bg = background
    c.colors.statusbar.normal.fg = foreground
    c.colors.statusbar.passthrough.bg = blue
    c.colors.statusbar.passthrough.fg = foreground
    c.colors.statusbar.private.bg = background
    c.colors.statusbar.private.fg = foreground
    c.colors.statusbar.progress.bg = foreground
    c.colors.statusbar.url.error.fg = red
    c.colors.statusbar.url.fg = foreground
    c.colors.statusbar.url.hover.fg = blue
    c.colors.statusbar.url.success.http.fg = foreground
    c.colors.statusbar.url.success.https.fg = gray
    c.colors.statusbar.url.warn.fg = red
    c.colors.tabs.bar.bg = background
    c.colors.tabs.even.bg = background
    c.colors.tabs.even.fg = foreground
    c.colors.tabs.indicator.error = red
    c.colors.tabs.indicator.system = 'none'
    c.colors.tabs.odd.bg = background
    c.colors.tabs.odd.fg = foreground
    c.colors.tabs.selected.even.bg = blue
    c.colors.tabs.selected.even.fg = foreground
    c.colors.tabs.selected.odd.bg = blue
    c.colors.tabs.selected.odd.fg = foreground
    c.colors.webpage.bg = foreground
    if qutewal_dynamic_loading or bool(os.getenv('QUTEWAL_DYNAMIC_LOADING')):
        import signal
        import subprocess
        import prctl
        qutewald = subprocess.Popen(
            [daemon_absolute, colors_absolute],
            preexec_fn=lambda: prctl.set_pdeathsig(signal.SIGTERM))
